#+STARTUP: indent
#+FILETAGS: readings

# Say what you want to say, just lay it out
* General intro
I read climate fiction because it's a need, the dissonance between what I think, how I feel and everyone else and everyday life is so striking I feel like I'm going crazy
The books make me feel like I'm not alone
Like my entire algo timeline is screaming climate collapse, there is no future but we're just like cows being led to slaughter chewing the cud
There's this huge uncertainty where the future and everything we know is in jeopardy and a buzzing uncertain overhanging ominous fear that's not clear at all and the books at least begin to cohere your thoughts, and begin to give shape to the fear shadows darkness and uncertainty, you begin to see it and maybe you also begin to see a way of renewal, a path out of the wilderness, the darkness

Climate fiction is a growing lit genre and reflects this need to imaginatively and emotionally digest the current dichotomy

I'm writing to digest and dig into my experience and impressions of the book and make it clearer to myself
I don't want to judge or rate this, I don't want to throw rocks at Markley but I probably will sound like it
Maybe I want to understand my needs more clearly in what I'm looking for

Purpose: gather and investigate personal impression of the book and why I felt overall lukewarm in it

* Impressions and experience of the book
Immediately what strikes me is the level of scientific and descriptive detail in the first few chapters with Tony
The beginning passages with Murdock and Shane with it's almost insane level of veteran lingo, bomb making parlance, made me think of a kind of hyper-realism
Petm Paleo Endo temperature maximum

I think for the first 3 or 5 chapters I was generally awestruck, I had like a growing feeling of like wow this is crazy

Hollywood symmetry, that's the term I'm looking for to describe climate collapse. He uses it in chapter 2 about Toy, the Iraqi bomb maker

* What I didn't like
The whole chapter about Kate and her movement and her speech disguised as an Vanity Fair article and her relationship with Matt is so fucking cringey. It feels like an adolescent comic book level. It's surprising because I thought the previous sections were so real somehow but this is just like too much

In The Days of Thunder and Rain part 2, hard to swallow the Fierce Blue Flame and how they raised so much money in 2 years and how powerful they are just because...? It's like a lack of something there.

* General conclusions?
Things are happening and some of the sequences are compelling and others are not but one thing that I notice is; in great books or stories, things seem to happen naturally or almost inevitably, maybe that has more to do with the classical fiction type of writing but with this book, I'm wondering why this is happening or why the writer chose to do this, it doesn't seem inevitable. I'm constantly like asking why?

I don't understand why there's a whole chapter of Matt and Kate's camping trip after Fierce Blue Fire, like it's doesn't need to be there? Like it doesn't add anything to the plot

Also didn't understand why Matt had to leave with Kate set on the occupation of the capitol, why and why now? It didn't make sense to me and the entire time I kept thinking he was a chump

Spent almost all of last week doing nothing but reading this book. At 880 pages, it is multi threaded, long winded, meandering, uneven work

* Characters
The story spans a decade in the lives of a few protagonists, Kate Morris a brash, in your face activist and her work with a Fierce Blue Flame

Matt, a writer and lover of Kate, who is more than anything a witness and just a POV sap for all of Kate's doings

A autistic spectrum quant Ash, who after his obsessions with basketball modeling moves betting moves into climate modeling and begins to work as a government technocrat

Tony Pietrus a scientist studying methane clathrates who becomes a spokesperson and figure head, his two daughters

Shane the eco-terroist and 6Degrees co-consiraptors

Keeper the drug addict who seems to be constantly going through a hellish landscape

Jacqueline who goes from Madison Ave marketing to work at the drecrepit offices of Kate Morris, after she becomes converted. Who betrays her financees hedge fund to a New Yorker writer

* Issues I had with the plot and pacing
The characters are loosely connected and the plot never seems to cohere really, it's a bunch of things that happen and you wonder if you had to know so much about each of the characters that necessarily didn't add or needed to be told maybe

There are whole chapters on Shane and Murdock's past meeting, Murdock comes off as a interesting super vivid character in the first of these chapters, effusing a whole patois and air of a disgruntled Iraqi war veteran but who just quickly fades away into a shadow in the rest of the 700 pages

Similarly, I wonder what need or color Jacqueline the genius marketing guru provided or added to the book and themes of the story, he one night stand, her working with the oil cartel group, her relationship with her mom and sisters, then her move to finance and dinner out with friends and gossip, and her mom's death by hanging and the flood. She didn't really play any significant role in the main plot, couldn't the entire sub-plot of her be taken out? After her conversion she worked with Kate but made no other real contribution

Speaking of she works her whole life in marketing bolstering capitalism, even going specifically against the Fierce Blue Fire and working with oil business consortium that calls itself the Sustainable Something Something, basically selling her soul for the devil and all but then she suddenly switched and I didn't understand why. It happened after her mom's suicide but the sudden change seems out of left field

Similarly Shane's flip flop between pushing for more targets regarless of human lives and then switching her mind and turning her entire crew in is inscrutable, one could make the argument that it was after she had to kill Allen and her son but the logic and the reasoning does not happen, it just seems like she wanted to take revenge after they decided to bomb her apartment

Matt's sudden break with Kate Morris when she comes up with the plan to take over DC's central lawn occupy is also wierd and hard to understand, in the book he makes it seem like he's worried for her of tired about her but after sticking with her so long and going through everything it also seems strange

It's messy, it's sprawling, it's inconclusive much like real life I guess
Many people have talked about how realistic this book was and how life like it's treatment



At a fundametnal level, it was like I couldn't really get into any of the characters or the characters felt empty and inconclusive

There is a drug dealer, a scientist, an activist, a writer, an eco-terrorist cell, a marketing exec, a hedge funder, a right wing preacher, somehow none of it coheres together

In the beginning 3 or 4 chapters through Tony, Murdock, and Keeper I was super engaged, thinking this is the book I wish I could have written about climate change. But a third of the way in, with Kate and Matt, and Jakie's threads being and the 6Degrees threads being added in kinda lost a narrative drive and felt like it was less really about climate change and more about these personalities... to me that's kinda boring.

There is a the LA megafire, Matt the writer's hurricane flooding, the Uncle Clive(?)'s real estate concerns, but overall climate change is something you see on the news, and something you hear (actually there is the dust storm and everything) about, it seems almost incidental. Kinda like how we currently experience it really. But I wanted maybe to have a different experience of it

Overlla the narrative and personality threads seem, haphazard, almost too realistic in that they don't accumulate or add up to something greater; the entire Jacqueline thread with her affair with the Preacher that comes up seems to add nothing really and that's like 200 pages that could have been taken out

It's like a maximalist work

Shane who took up so much of the earlier and middle parts of the book seem to just disappear and melt away

For all the emphasis given Kate Morris and her team, it's hard to say what she actually does or accomplishes, the failed alliance with the Republican presidential candidate, the activst work that's kinda talked about but not detailed (lightly), the failed DC occupation, it's more of a cult of personality that she and Markley seems to represent

The bulk of any real climate action is done legislatively with Tony and Hasan, and due to the climate impacts
It's very wonky in terms of the political stuff and legislation that needs to happen and entire chapters are devoted to the particulars and the various factions

Even though the suicide bombing by Keeper and 6Degrees of Senator Murkowski does help to remove an obstable to the final legsislation

It kinda feel like in a similar way to the Ministry for the Future, that the narrative threads sprial out of focus. There's no tightness there but perhaps that's just the nature of something so multithreaded or with a kind of writing like this where the fidelity to reality is a large focus

I think the entire time, I felt like something was missing and I guess the things that was missing was the motive force behind the characters; it was strange and almost unspoken why they were climate change activists, and when Kate or someone does speak of it it sounds like collegiate liberal sentiments and thinking. There was very little of Tony's and Kate's or anyone else's feelings, impressions, the kind of the tactile tendrils of life that helps you to inhabit and understand their motivations. I think was I missed was the kind of personal, pyschological, grief and reckoning that I feel like I deal with and the disjunct I feel of every day life, the surreality of it.

The book instead moves from climate change to the actions of the characters, like they are super heroes, there is no beginning
Or they move from climate change as a given to the actions of the characters immediately... I think maybe something missing is the feeling of grief and loss, a world and a life lost

I guess maybe that's what I was looking for, less of a climate change hero novel, and more of a climate change this is what it feels like, and how surreal is this and how weird is it kind of story.

It kinda pushes this narrative where everyday people are obstables and bystanders, the only people who are doing anything or can play a significant part are activists, extremists, and politicians. Really didn't like the emphasis and centering of non-civilians

I thought the book was full of heart, big risks, unevenly stupendous and ambitious

For fiction I think I look for a kind of deeper interiority, because that's what it can do or maybe it's what modernism has accustomed us to, but Markley's writing is not that at all

His kind of hyper realism seems to be more about the modern hemingway type of writing or whatever that is, I mean the novel stylistically kind of reminded me of something like Scorpio, dark, gripping realism minus the kind of poetic or liminal writing
He for example will always describe a graphic tee someone is wearing

* Final conclusions
I admire him a lot, I admire his ambition, his tenacity, his completion of his book
